### ISSUE TITLE
k8s namespaces, oidc login not working

### ISSUE THREAD

**Issue by umberto10** [tinyzimmer/kvdi#17] opened 2021-02-02 10:24 UTC
When I set up namespace for chart and app, main page (after OIDC login) starts to refreshing all the time. It works only in default namespace which I don't want to use. Am I doing something wrong? I tested it on the same namespace for app and chart, and also for different ones. Please help.

**Comment by tinyzimmer** [comment] 2021-02-02 10:44
With OIDC there are a lot of variables at play that could cause that.

`vdi.spec.auth.tokenDuration` you almost certainly want to set to a high value (e.g. `8h`) if you haven't set it at all. There is no way for the refresh token logic to work with the OIDC flow, so when your login token expires it has to login all over again. The default is 15 minutes IIRC.

As for only being able to use the `default` namespace, depends on the role that is assigned to you when you login. If you are an admin or assuming a VDIRole that can access other namespaces, then you might have found a bug.  For reference, the [example in the repo](https://github.com/tinyzimmer/kvdi/blob/main/hack/oidc-role.yaml) would allow all namespaces if you are in the `authors` group on the OIDC provider. The [other configurations](https://github.com/tinyzimmer/kvdi/blob/main/doc/crds.md#OIDCConfig) might be coming into play too. For instance, if you are using the `allowNonGroupedReadOnly` config, I might need to check if that allows all namespaces or just `default`.

If you are still having trouble after all that, posting your configurations might help me diagnose further.

**Comment by umberto10** [comment] 2021-02-02 11:18
I'm using `allowNonGroupedReadOnly` config, with custom user attributes for mapping admin role. And if I change app namespce from default, it doesn't work. Maybe I should use [this, as u said,](https://github.com/tinyzimmer/kvdi/blob/main/hack/oidc-role.yaml) for both, admin and normal users. This is my current config:
`    auth:
      tokenDuration: "10h"
      oidcAuth:
        issuerURL: "https://url"
        clientCredentialsSecret: "oidc-secret-kvdi"
        redirectURL: "https://url/api/login"
        tlsInsecureSkipVerify: True
        groupScope: kvdi-policy
        adminGroups: [ "admin-user" ]
        allowNonGroupedReadOnly: True`

**Comment by tinyzimmer** [comment] 2021-02-02 11:25
Yep that makes sense.

I had to go looking again because I haven't touched that part of the code in a while, but the "default user role" that gets created with a cluster is the same as the one that gets matched up to users that don't have a "group" with OIDC and its allowed. Where it gets defined is nice and centralized already [here](https://github.com/tinyzimmer/kvdi/blob/d2546dabcd0e5ebf2305e3d6c784f9a4aa58cb7c/pkg/apis/kvdi/v1alpha1/vdicluster_auth_util.go#L120:22) which is a nice plus. It does default to only allowing whatever the `appNamespace` is.

I'm wondering if this should be configurable. I.e. allow the user to specify custom rules for the default role. It would satisfy this use case, make the OIDC more flexible as a result, and be a nice addition to the API.

I'll probably take a stab at it this week or next when I'm looking at the other issues.

**Comment by tinyzimmer** [comment] 2021-02-02 11:33
Wait just to make sure I'm understanding, cuz I might have gotten confused by the edit, is the constant refresh happening even with `tokenDuration` set to `10h`?

**Comment by umberto10** [comment] 2021-02-02 11:36
Yup, there are literally only 302 response codes in app logs. Page is refreshing all the time, and I can't do anything in web gui. My OIDP says that session is established, but I can't see it in gui, because of refreshes.

**Comment by tinyzimmer** [comment] 2021-02-02 11:39
Was the `tokenDuration` changed though? Because if so, you probably want to do a hard refresh (no-cache, e.g. Shift+F5 or new tab/window) so you can get a new token with the correct duration.

If the duration was set to `10h` all along and that is the behavior, then yea you definitely found a bug that I might need help reproducing.

**Comment by umberto10** [comment] 2021-02-02 11:39
> Yep that makes sense.
> 
> I had to go looking again because I haven't touched that part of the code in a while, but the "default user role" that gets created with a cluster is the same as the one that gets matched up to users that don't have a "group" with OIDC and `allowNonGroupedReadOnly` is `true`. Where it gets defined is nice and centralized already [here](https://github.com/tinyzimmer/kvdi/blob/d2546dabcd0e5ebf2305e3d6c784f9a4aa58cb7c/pkg/apis/kvdi/v1alpha1/vdicluster_auth_util.go#L120:22) which is a plus. It does default to only allowing whatever the `appNamespace` is.
> 
> I'm wondering if this should be configurable. I.e. allow the user to specify custom rules for the default role. It would satisfy this use case, make the OIDC more flexible as a result, and be a nice addition to the API.
> 
> I'll probably take a stab at it this week or next when I'm looking at the other issues.

So, if i try disable `allowNonGroupedReadOnly`, create VDIRole and assign user attributes from OIDP to them, it should work?

**Comment by tinyzimmer** [comment] 2021-02-02 11:41
If by "assign user attributes from OIDP" you mean provide some sort of "group" field matched up to roles you define like the example instead, then yea it will solve that issue. 

I'll probably still make that default role customizable anyway because I kinda like the idea.

**Comment by umberto10** [comment] 2021-02-02 11:44
I don't use groups in my OIDP, I'm using user attributes (key: value fiels) instead

**Comment by umberto10** [comment] 2021-02-02 11:47
> Was the `tokenDuration` changed though? Because if so, you probably want to do a hard refresh (no-cache, e.g. Shift+F5 or new tab/window) so you can get a new token with the correct duration.
> 
> If the duration was set to `10h` all along and that is the behavior, then yea you definitely found a bug that I might need help reproducing.

It is working after uninstalling and deletion pv of all containers from kvdi!
Thanks, for your help

**Comment by tinyzimmer** [comment] 2021-02-02 12:00
Reopening so I remember the other idea that came up 😄

**Comment by tinyzimmer** [comment] 2021-02-02 12:01
> I don't use groups in my OIDP, I'm using user attributes (key: value fiels) instead

Gotcha, yea. You are doing what I intended to be possible 😛 for people that don't have "groups".

**Closed** 2021-02-05 11:40 UTC
